# Generated by Django 2.1.7 on 2019-07-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herald_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='messenger',
            field=models.IntegerField(choices=[(0, 'Telegram'), (1, 'Viber'), (2, 'VK'), (3, 'Facebook')], verbose_name='Мессенджер'),
        ),
    ]
