# Generated by Django 2.1.7 on 2019-07-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herald_bot', '0004_auto_20190707_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('Русский', 'Русский'), ('English', 'English')], max_length=16, null=True, verbose_name='Язык'),
        ),
    ]
