# Generated by Django 2.1.7 on 2019-07-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herald_bot', '0005_auto_20190707_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.IntegerField(blank=True, choices=[(0, 'Русский'), (1, 'English')], null=True, verbose_name='Язык'),
        ),
    ]
