# Generated by Django 2.1.7 on 2019-07-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herald_bot', '0007_auto_20190709_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('ru', 'Русский'), ('en', 'English')], max_length=16, null=True, verbose_name='Язык'),
        ),
    ]
